### ISSUE TITLE
[Bug] Grafana 8 container differs from Grafana 7 container, issues with grafana-operator

### ISSUE THREAD

**Issue by Cellebyte** [bitnami/bitnami-docker-grafana#17]
**Description**

The uid changed from `1001` to `grafana` which is `999` in the `/opt/bitnami/grafana` directory.

Is that intended?

Also the behavior of the grafana plugin install script changed from `exit 0` to `return` and no exit.

https://github.com/bitnami/bitnami-docker-grafana/blob/124b4f2377dd3dd883ac10c3180a9fa5b7274d03/8/debian-10/rootfs/run.sh#L45

https://github.com/bitnami/bitnami-docker-grafana/blob/435072922f84a685b267d963d3ffe56381c2d786/8/debian-10/rootfs/opt/bitnami/scripts/libgrafana.sh#L105

This breaks compatibility.
**Steps to reproduce the issue:**

Install this chart
- [https://github.com/bitnami/charts/pull/8059](https://github.com/bitnami/charts/pull/8059)

**Describe the results you received:**

The plugin init pod crashed because it expects another uid to create the file.
After changing the uid in the deployment to `999` it worked.

Then the init pod does not get terminated as the old one did so the initcontainer is not successfully ended.

**Describe the results you expected:**

smooth installation of plugins in grafana8 and after plugin initialization a termination of the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

```console
$ podman run -it -e GF_OP_PATHS_CONFIG=test --entrypoint="" docker.io/bitnami/grafana:7.3.6-debian-10-r20 bash
1001@4648bf448204:/opt/bitnami/grafana$ ls
LICENSE  NOTICE.md  README.md  VERSION  bin  conf  data  default-plugins  licenses  logs  plugins-bundled  public  scripts

1001@4648bf448204:/opt/bitnami/grafana$ cd data/

1001@4648bf448204:/opt/bitnami/grafana/data$ ls -lah
total 0
drwxrwxr-x 1 1001 root 14 Jan  7  2021 .
drwxr-xr-x 1 1001 1001 38 Jan  7  2021 ..
drwxrwxr-x 1 root root  0 Jan  7  2021 plugins

1001@4648bf448204:/opt/bitnami/grafana$ getent passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
1001:*:1001:0:container user:/opt/bitnami/grafana:/bin/sh
```
```console
$ podman run -it -e GF_OP_PATHS_CONFIG=test docker.io/bitnami/grafana:8.2.5-debian-10-r6 bash                      INT ✘ 
grafana 18:00:18.38 
grafana 18:00:18.38 Welcome to the Bitnami grafana container
grafana 18:00:18.38 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-grafana
grafana 18:00:18.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-grafana/issues
grafana 18:00:18.38 

1001@d4b2666f7c3c:/opt/bitnami/grafana$ ls -lah data/
total 0
drwxrwxr-x 1 grafana root 14 Nov 24 15:07 .
drwxr-xr-x 1 root    root 54 Nov 24 15:07 ..
drwxrwxr-x 1 grafana root  0 Nov 24 15:07 plugins

1001@d4b2666f7c3c:/opt/bitnami/grafana$ getent passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
grafana:x:999:999::/home/grafana:/bin/sh
1001:*:1001:0:container user:/opt/bitnami/grafana:/bin/sh
```

**Comment by miguelaeh** [comment]
Hi @Cellebyte ,

I understand you are upgrading from `7` to `8`, i.e. between two major versions. The upgrade between major versions usually requires some manual intervention. The steps should be listed in the Grafana upgrading guides.

Apart from that, I just run the image like:
```
 docker run --rm -it bitnami/grafana:8 bash
```

And then `whoami`, it seems to be still `1001`. Could you provide more info on how did you get `999`?

**Comment by Cellebyte** [comment]
@miguelaeh the issue is not the `whoami` command as you can see in my Issue.
The contiainer user with the uid `1001` is still created.

But if you list the ` ls -lah /opt/bitnami/grafana/data` directory and so on it is owned by the wrong user.

**Comment by Cellebyte** [comment]
The other issue changed the behavior of an init script which does not exit the container after plugin install.
Both of them got introduced with the new version and are not related to the grafana version.

**Comment by Cellebyte** [comment]
@miguelaeh please have a look. It is still broken.

**Comment by nehaLohia27** [comment]
@miguelaeh I am also observing the same behaviour while upgrading from grafana-operator bitnami chart from 3.10 to 4.0.2 . Please take a look. @Cellebyte Thanks for providing the root cause.  @Cellebyte Can you provide me the steps used for upgrading this charts ?

**Comment by miguelaeh** [comment]
Hi guys,
I am trying to understand the issue yet. The `/opt/bitnami/grafana/data` directory is a mounted volume by the chart. The permissions for that directory could be set using `fsGroup`, or in some clusters where it doesn't work, enabling the [volumePermissions](https://github.com/bitnami/charts/blob/576b48e07855e128a9be7c8e55dec563b69abf5e/bitnami/grafana/templates/deployment.yaml#L78) init container.

Sorry for not being too helpful this time, but I still don't understand the issue. It would be nice if you can provide the steps to reproduce it on our side.

**Comment by Cellebyte** [comment]
@miguelaeh here is an example manifest to test it.

kubectl apply -f this.yaml -n test-grafana

```yaml
---
apiVersion: v1
items:
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/instance: grafana-operator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana-operator
      helm.sh/chart: grafana-operator-2.0.0
    name: grafana-operator

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: grafana-serviceaccount

kind: List
---
apiVersion: v1
items:
- apiVersion: v1
  data:
    grafana.ini: |+
      [alerting]
      enabled = false

      [analytics]
      check_for_updates = false
      reporting_enabled = false

      [log]
      level = warn
      mode = console

      [paths]
      data = /var/lib/grafana
      logs = /var/log/grafana
      plugins = /var/lib/grafana/plugins
      provisioning = /etc/grafana/provisioning/

      [security]
      disable_gravatar = false

      [server]
      root_url = http://localhost:3000

  kind: ConfigMap
  metadata:
    name: grafana-config

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: grafana-datasources

kind: List
---
apiVersion: v1
items:
- apiVersion: v1
  data:
    GF_SECURITY_ADMIN_PASSWORD: allnaUR6ZDRIVUM5Vmc9PQ==
    GF_SECURITY_ADMIN_USER: YWRtaW4=
  kind: Secret
  metadata:
    name: grafana-admin-credentials

  type: Opaque
kind: List
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: grafana
    app.kubernetes.io/instance: grafana-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana-operator
    helm.sh/chart: grafana-operator-2.0.0
    pod-template-hash: 9d865c647
  name: grafana-deployment-9d865c647-8xgp7
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: grafana
              app.kubernetes.io/instance: grafana-operator
              app.kubernetes.io/name: grafana-operator
          namespaces:
          - asdf
          topologyKey: kubernetes.io/hostname
        weight: 1
  containers:
  - args:
    - -config=/etc/grafana/grafana.ini
    env:
    - name: LAST_CONFIG
      value: 714b3e28131c5eb375f17c78cc9f7f3c3978c47732c4653daef2a34647f0902a
    - name: LAST_DATASOURCES
    - name: GF_SECURITY_ADMIN_USER
      valueFrom:
        secretKeyRef:
          key: GF_SECURITY_ADMIN_USER
          name: grafana-admin-credentials
    - name: GF_SECURITY_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          key: GF_SECURITY_ADMIN_PASSWORD
          name: grafana-admin-credentials
    image: docker.io/bitnami/grafana:8.3.0-debian-10-r0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 6
      httpGet:
        path: /api/health
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 5
    name: grafana
    ports:
    - containerPort: 3000
      name: grafana-http
      protocol: TCP
    readinessProbe:
      failureThreshold: 6
      httpGet:
        path: /api/health
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 5
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 1001
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/grafana/
      name: grafana-config
    - mountPath: /var/lib/grafana
      name: grafana-data
    - mountPath: /var/lib/grafana/plugins
      name: grafana-plugins
    - mountPath: /etc/grafana/provisioning/plugins
      name: grafana-provision-plugins
    - mountPath: /etc/grafana/provisioning/dashboards
      name: grafana-provision-dashboards
    - mountPath: /etc/grafana/provisioning/notifiers
      name: grafana-provision-notifiers
    - mountPath: /var/log/grafana
      name: grafana-logs
    - mountPath: /etc/grafana/provisioning/datasources
      name: grafana-datasources
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hhngd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - env:
    - name: GRAFANA_PLUGINS
    image: docker.io/bitnami/grafana:8.3.0-debian-10-r0
    imagePullPolicy: IfNotPresent
    name: grafana-plugins-init
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/plugins
      name: grafana-plugins
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hhngd
      readOnly: true
  nodeName: schiff-cp-swe-md-0-5789d8bf58-59ksr
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    runAsUser: 1001
  serviceAccount: grafana-serviceaccount
  serviceAccountName: grafana-serviceaccount
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: grafana-provision-plugins
  - emptyDir: {}
    name: grafana-provision-dashboards
  - emptyDir: {}
    name: grafana-provision-notifiers
  - configMap:
      defaultMode: 420
      name: grafana-config
    name: grafana-config
  - emptyDir: {}
    name: grafana-logs
  - emptyDir: {}
    name: grafana-data
  - emptyDir: {}
    name: grafana-plugins
  - configMap:
      defaultMode: 420
      name: grafana-datasources
    name: grafana-datasources
  - name: kube-api-access-hhngd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace

```
